language: node_js
before_install:
 - openssl aes-256-cbc -K $encrypted_d00969f14040_key -iv $encrypted_d00969f14040_iv
  -in deploy_rsa.enc -out deploy_rsa -d

install: true
 - npm install

script:
 - chmod 600 deploy_rsa
 - ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
 - ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR 'bash -s' < deploy.sh
